framework:
    rate_limiter:
        product_description_api:
            policy: sliding_window
            limit: 30
            interval: '1 minute'
            cache_pool: rate_limiter.cache
        product_description_status_api:
            policy: sliding_window
            limit: 120
            interval: '1 minute'
            cache_pool: rate_limiter.cache

when@test:
    framework:
        rate_limiter:
            product_description_api:
                policy: sliding_window
                limit: 10
                interval: '1 minute'
                cache_pool: rate_limiter.cache
            product_description_status_api:
                policy: sliding_window
                limit: 20
                interval: '1 minute'
                cache_pool: rate_limiter.cache
